check if clientHints is undefined on parser>>device>device-trusted.js
sanchezzzhak/node-device-detector pull request #204
Opened 2024-10-05 00:33 UTC by gilsongabriel

this pr add check for var clientHints.clients in function check in the class DeviceTrusted, the var maybe can be undefined when http request came from a browser is installed on macOS and macOS is installed in a not authentic apple hardware.

![image](https://github.com/user-attachments/assets/66dd41d4-db63-45d6-a0e3-ab2862ecac84)

2024-10-07 09:01 UTC, sanchezzzhak requested changes

2024-10-07 09:01 UTC, sanchezzzhak commented on tests/fixtures/oss.yml
need remove new fixture item
the file automatic update by script tests/tools/update-fixtures

if you need test fixtures use next files
/tests/fixturtes/devices/ext-smartphone.yml
/tests/fixturtes/devices-trusted/fixture-0.yml

2024-10-07 09:05 UTC, sanchezzzhak approved these changes

2024-10-07 09:07 UTC, sanchezzzhak approved these changes

2024-10-07 09:22 UTC, merged

2024-10-08 01:06 UTC, gilsongabriel commented on tests/fixtures/oss.yml
ok, sorry, I didn't pay attention to that